version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: fazt
      POSTGRES_PASSWORD: faztpassword
      POSTGRES_DB: productsdb
    # volumes:
    #   - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432